version: "3"
services:
  node:
    container_name: ui_map
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:3000
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
