version: "3"
services:
  ui:
    container_name: ui
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:1880
      - REACT_APP_GRAFANA_DASHBOARD_URL=http://localhost:9000/d/OodDRfonk/workshop-application?orgId=1&from=now-6h&to=now&refresh=1m
      - REACT_APP_REFRESH_INTERVAL=60 # (seconds)
    volumes:
      - ./src/:/home/node/app/src
    healthcheck:
      test: ["CMD", "curl", "-s", "localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s